# Generated by Django 5.2.13 on 2026-04-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('MEMORY_MATCH', 'Memory Match'), ('SPATIAL_REASONING', 'Spatial Reasoning'), ('PATTERN_SEQUENCE', 'Pattern Sequence')], max_length=50)),
                ('score', models.IntegerField()),
                ('duration_seconds', models.IntegerField()),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('metrics', models.JSONField(help_text='Detailed gameplay metrics (clicks, errors, etc.)')),
            ],
        ),
    ]
