# Generated by Django 5.2.13 on 2026-04-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateTimeField(auto_now_add=True)),
                ('overall_score', models.IntegerField()),
                ('memory_score', models.IntegerField()),
                ('attention_score', models.IntegerField()),
                ('orientation_score', models.IntegerField()),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MODERATE', 'Moderate Risk'), ('HIGH', 'High Risk')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('MEMORY', 'Memory'), ('PATTERN', 'Pattern'), ('ORIENTATION', 'Orientation')], max_length=20)),
                ('correct_answer', models.CharField(max_length=255)),
                ('options', models.JSONField(help_text='Provide a list of options as JSON')),
            ],
        ),
    ]
