# Generated by Django 5.2.13 on 2026-04-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CognitiveTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('rolling_memory_average', models.FloatField()),
                ('rolling_attention_average', models.FloatField()),
                ('risk_velocity', models.FloatField(help_text='Rate of change in cognitive score over time')),
            ],
        ),
        migrations.CreateModel(
            name='DailyWellness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('mood_score', models.IntegerField(blank=True, null=True)),
                ('activity_level', models.CharField(blank=True, max_length=50, null=True)),
                ('recommendation', models.TextField(help_text='AI-generated recommendation based on metrics')),
            ],
        ),
    ]
