# Generated by Django 5.2.13 on 2026-04-20 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cognitivetrend',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='users.patientprofile'),
        ),
        migrations.AddField(
            model_name='dailywellness',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_logs', to='users.patientprofile'),
        ),
    ]
